### ISSUE TITLE
Extra arguments for a queue

### ISSUE THREAD

**Issue by gustavosbarreto** [cheshir/go-mq#16]
How to pass extra arguments for a queue?

I tried the following configuration without success:

```yaml
queues:
    - name: "uh.traffic.limit_workers"
      exchange: "uh.api.events"
      routing_key: "namespaces_activity"
      options:
        durable: true
        args:
          'x-max-priority': 9
```
